version: "3.7"
services:
  # browser-test:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   image: automerge-swarm:latest
  #   environment:
  #     - "PORT=3000"
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./packages/automgerge-swarm/bin:/app/packages/automerge-swarm/bin
  #     - ./packages/automgerge-swarm/src:/app/packages/automerge-swarm/src
  #     - ./packages/automgerge-swarm/types:/app/packages/automerge-swarm/types
  #     - ./packages/automgerge-swarm-redux/src:/app/packages/automerge-swarm-redux/src
  #     - ./examples/browser-test/public:/app/examples/browser-test/public
  #     - ./examples/browser-test/src:/app/examples/browser-test/src
  #   stdin_open: true
  #   working_dir: /app/examples/browser-test
  #   command:
  #     - npm
  #     - start
  wiki-swarm:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: automerge-swarm:latest
    environment:
      - "PORT=3000"
    ports:
      - 3000:3000
    volumes:
      - ./packages/automerge-swarm/bin:/app/packages/automerge-swarm/bin
      - ./packages/automerge-swarm/src:/app/packages/automerge-swarm/src
      - ./packages/automerge-swarm/types:/app/packages/automerge-swarm/types
      - ./packages/automerge-swarm-redux/src:/app/packages/automerge-swarm-redux/src
      - ./examples/wiki-swarm/public:/app/examples/wiki-swarm/public
      - ./examples/wiki-swarm/src:/app/examples/wiki-swarm/src
    stdin_open: true
    working_dir: /app/examples/wiki-swarm
    command:
      - npm
      - start
  node:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: automerge-swarm:latest
    ports:
      - 4001:4001
      - 4002:4002
      - 4003:4003
    volumes:
      - ./packages/automerge-swarm/bin:/app/packages/automerge-swarm/bin
      - ./packages/automerge-swarm/src:/app/packages/automerge-swarm/src
      - ./packages/automerge-swarm/types:/app/packages/automerge-swarm/types
  star-signal:
    build:
      context: ./
      dockerfile: ./Dockerfile.webrtc-star-signal
    image: automerge-swarm-signal:latest
    ports:
      - 9090:9090
